version: '3.3'
services:
  lodestar-node:
    restart: on-failure
    build: ./bin
    ports:
      - '8089:8089'
      - '8090:8090'
  lodestar-nginx:
    build: ./nginx
    ports:
    - '82:80'
    depends_on:
    - lodestar-node
    volumes:
    - './www:/var/www/html/'
    - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    - 'leaflet:/var/www/html/leaflet'
    dns: 8.8.8.8

volumes:
  leaflet:

